title: Brains@Play
email: contact@brainsatplay.com
description: >- # this means to ignore newlines until "baseurl:"
  Brains@Play enables the responsible development of brain-responsive multiplayer experiences. Explore, create, and share BCI games on the web!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brainsatplay.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brainsatplay
github_username:  brainsatplay

# Build settings
theme: minima
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
